### PR TITLE
Changed every origin='image' to origin='lower'. Fix 

### LINKED ISSUE #11: Old keywords in plt.imshow functions
There are many instances of the keyword origin='image' with the function plt.imshow(). This causes an error because it's no longer supported. The correct new keyword is origin='lower'. For example here on line 303:

https://github.com/Probe-Particle/PPSTM/blob/03449bd70aeaf0f466ac7525dcdc9ac4c28d73fb/PPSTM_simple.py#L300-L306

### PR DESCRIPTION
**Pull request by LauriKurki**
Changed every instance of origin='image' to origin='lower' as 'image' is no longer a supported keyword. Fixes #11

### CODE REVIEW

**Review by ondrejkrejci — COMMENTED** [review]
Thank's for spotting it - did you tried those tests? If so, then I will pass it through.

**Comment by LauriKurki** [comment]
I ran the tests now but all of the relaxed scans fail because PPAFM has been changed. For example the LJ field for relaxed scan used to be generated with `python PATH_TO_YOUR_PROBE_PARTICLE_MODEL/generateLJFF.py -i YOUR_INPUT_FILE.cube --npy` but the `--npy` option has been replaced with `-f npy`.  I will fix this in another issue/pull request but the changes in this pull request shouldn't change anything in the behaviour of PPSTM.

Also, something seems to have been changed in the way the force field is saved within PPAFM as line 390 in pyProbeParticle/GridUtils raises "IndexError: string index out of range". I will look into this.

https://github.com/Probe-Particle/ProbeParticleModel/blob/34e6a3603bfe4759fa68a0641ae202c30f64e778/pyProbeParticle/GridUtils.py#L382-L390

**Comment by ondrejkrejci** [comment]
Perfect. At least it is good to check on the non-relaxing examples. Thanks a lot @LauriKurki - Ok. I will approve now. The strategy with the new issue is a good one! If we run into some problems with the GridUtils of PPAFM we can also start a new issue on the PPAFM repository!

**Review by ondrejkrejci — APPROVED** [review]
Thank you!

**Comment by ondrejkrejci** [comment]
We should generally use the second merge option - **Squash and merge** , this way many commits from the pull/merge request wil come into one.

**Pull request merged**
