### PR TITLE
trying to omit forbitals from CP2K reading

### PR DESCRIPTION
**Pull request by ondrejkrejci**
solves #26 
I have runned the CuPc test and it went through. Cannot say that it will work or not,

### CODE REVIEW

**Review by ondrejkrejci — COMMENTED** [review]
It looks good to me. Have you run at least some of the tests? If so, we can squish and merge.  (and sorry for the other typo).

**Review by LauriKurki — APPROVED** [review]
Didn't run tests but looks good, I added two more changes. 

1. Changed the else statement to report the specific error in case the orbital is not recognized. 

2. fix typo `func.endwith` -> `func.endswith`

**Comment by ondrejkrejci** [comment]
I will quickly run the one test then, just to be sure.

**Comment by LauriKurki** [comment]
I ran the TOAT and CuPC tests, no problems there

**Pull request merged**
