### PR TITLE
Fixed lattice vector assert in for_PBC

### PR DESCRIPTION
**Pull request by LauriKurki**
Checks that lvs is not None and its size isn't zero

### CODE REVIEW

**Comment by ondrejkrejci** [comment]
There is a way in the top-right corner, how you can assign review ...

**Review by ondrejkrejci — COMMENTED** [review]
Have you tried to run the Si7x7 example?

**Comment by LauriKurki** [comment]
I checked the tests now. On master branch the Si test fails, and with this fix the tests ran ok.

**Review by ondrejkrejci — APPROVED** [review]
Good from my side then.

**Pull request merged**
